# Generated by Django 5.0.6 on 2025-10-15 01:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tickets', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.SlugField(help_text='Código único del tipo de notificación', unique=True)),
                ('nombre', models.CharField(help_text='Nombre descriptivo del tipo', max_length=100)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del tipo de notificación')),
                ('es_activo', models.BooleanField(default=True, help_text='Indica si este tipo está activo')),
                ('enviar_a_cliente', models.BooleanField(default=False, help_text='Se envía al cliente del ticket')),
                ('enviar_a_tecnico', models.BooleanField(default=False, help_text='Se envía al técnico asignado')),
                ('enviar_a_admin', models.BooleanField(default=False, help_text='Se envía al administrador')),
            ],
            options={
                'verbose_name': 'Tipo de Notificación',
                'verbose_name_plural': 'Tipos de Notificaciones',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título de la notificación', max_length=200)),
                ('mensaje', models.TextField(help_text='Contenido del mensaje')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENVIADA', 'Enviada'), ('LEIDA', 'Leída'), ('FALLIDA', 'Fallida')], default='PENDIENTE', help_text='Estado actual de la notificación', max_length=20)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora de creación de la notificación')),
                ('fecha_envio', models.DateTimeField(blank=True, help_text='Fecha y hora de envío de la notificación', null=True)),
                ('fecha_lectura', models.DateTimeField(blank=True, help_text='Fecha y hora de lectura de la notificación', null=True)),
                ('datos_adicionales', models.JSONField(blank=True, default=dict, help_text='Datos adicionales en formato JSON para contexto')),
                ('ticket', models.ForeignKey(blank=True, help_text='Ticket relacionado con la notificación', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='tickets.ticket')),
                ('usuario', models.ForeignKey(help_text='Usuario destinatario de la notificación', on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
                ('tipo', models.ForeignKey(help_text='Tipo de notificación', on_delete=django.db.models.deletion.PROTECT, related_name='notificaciones', to='notifications.notificationtype')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['usuario', 'estado'], name='notificatio_usuario_8f60bb_idx'), models.Index(fields=['fecha_creacion'], name='notificatio_fecha_c_929fc4_idx'), models.Index(fields=['ticket', 'tipo'], name='notificatio_ticket__4644c7_idx')],
            },
        ),
    ]
