# Generated by Django 5.0.6 on 2025-10-17 21:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción breve de la notificación'),
        ),
        migrations.AddField(
            model_name='notification',
            name='enviado_por',
            field=models.ForeignKey(blank=True, help_text='Usuario que envió la notificación (técnico o administrador)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones_enviadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='enviado_por_role',
            field=models.CharField(blank=True, help_text='Rol del usuario que envió la notificación', max_length=20),
        ),
    ]
