# Generated by Django 5.0.6 on 2025-10-17 22:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_descripcion_notification_enviado_por_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='destinatarios',
            field=models.ManyToManyField(blank=True, help_text='Usuarios destinatarios de la notificación (uno o varios)', related_name='notificaciones_recibidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='enviado_por_role',
            field=models.CharField(blank=True, help_text='Rol del usuario que envió la notificación', max_length=20, null=True),
        ),
    ]
