# Generated by Django 5.0.6 on 2025-10-18 00:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_destinatarios_and_more'),
        ('tickets', '0003_alter_ticket_administrador_alter_ticket_cliente_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='datos_adicionales',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='notification',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='destinatarios',
            field=models.ManyToManyField(blank=True, related_name='notificaciones_recibidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='enviado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones_enviadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='enviado_por_role',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENVIADA', 'Enviada'), ('LEIDA', 'Leída'), ('FALLIDA', 'Fallida')], default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='notification',
            name='fecha_envio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='fecha_lectura',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='mensaje',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='notification',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='tickets.ticket'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notificaciones', to='notifications.notificationtype'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='notification',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notificationtype',
            name='codigo',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='notificationtype',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='notificationtype',
            name='enviar_a_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notificationtype',
            name='enviar_a_cliente',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notificationtype',
            name='enviar_a_tecnico',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notificationtype',
            name='es_activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='notificationtype',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
