# Generated by Django 5.2.6 on 2025-10-02 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='user',
            name='document',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
