# Generated by Django 5.0.6 on 2025-10-18 21:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_alter_ticket_administrador_alter_ticket_cliente_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StateChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('rejected', 'Rechazado')], default='pending', max_length=20)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='state_requests_approved', to=settings.AUTH_USER_MODEL)),
                ('from_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_from', to='tickets.estado')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_requests_made', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_requests', to='tickets.ticket')),
                ('to_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_to', to='tickets.estado')),
            ],
            options={
                'verbose_name': 'Solicitud de Cambio de Estado',
                'verbose_name_plural': 'Solicitudes de Cambio de Estado',
                'ordering': ['-created_at'],
            },
        ),
    ]
