# Generated by Django 5.0.6 on 2025-11-03 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_statechangerequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=50)),
                ('estado_anterior', models.CharField(blank=True, max_length=50, null=True)),
                ('accion', models.CharField(max_length=200)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('datos_ticket', models.JSONField(blank=True, help_text='Datos del ticket al momento de la acción', null=True)),
                ('realizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acciones_realizadas', to=settings.AUTH_USER_MODEL)),
                ('tecnico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historiales_como_tecnico', to=settings.AUTH_USER_MODEL)),
                ('tecnico_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historiales_como_tecnico_anterior', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='tickets.ticket')),
            ],
            options={
                'verbose_name': 'Historial de Ticket',
                'verbose_name_plural': 'Historiales de Tickets',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['ticket', '-fecha'], name='tickets_tic_ticket__bb74fc_idx')],
            },
        ),
    ]
