# Generated by Django 5.0.6 on 2025-11-20 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_remove_estado_6'),
        ('tickets', '0005_tickethistory'),
    ]

    operations = [
    ]
